spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/shopnest
    name: coupons
    password: Suvam@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
  application:
      name: coupons-module      
     
server:
  port: '8081'
 
# Eureka 
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

# Okta Configuration
okta:
  oauth2:
    issuer: https://dev-52786026.okta.com/oauth2/default
    audience: api://default