spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/poc_schema
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9001
  servlet:
    context-path: /account-service

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,metrics,info
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  metrics:
    enable:
      resilience4j:
        circuitbreaker:
          calls: true
  health:
    circuitbreakers:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


resilience4j.circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      employeeServiceCircuitBreaker:
        base-config: default
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
#        slow-call-rate-threshold: 40
#        max-wait-duration-in-half-open-state: 5s
#        slow-call-duration-threshold: 2s
#        writable-stack-trace-enabled: true


