server:
  port: 8787
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajayv2/conf-ser-repo.git
          clone-on-start: true
          default-label: main
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
