server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes[0]:
        id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates[0]: Path=/api/employee/**
      routes[1]:
        id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates[0] : Path=/api/departments/**
      routes[2]:
        id: ORGANIZATION-SERVICE
        uri: lb://ORGANIZATION-SERVICE
        predicates[0] : Path=/api/organization/**
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
