spring:
  application:
    name: shutterstockApi-image-footage

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/sstk_image_footage
    username: root
    password: Sstk@2024
    driver-class-name: com.mysql.cj.jdbc.Driver

    minimumIdle: 30
    maximumPoolSize: 100
    idleTimeout: 10000
    connectionTimeout: 30000
    poolName: ShutterstockHikariCP

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

logging:
  file:
    name: sstk-if.log