spring:
  application:
    name: shutterstockApi

  datasource:
    url: jdbc:mysql://shutterstock-db.ctgq828si44a.ap-south-1.rds.amazonaws.com:3306/shutterstock
    username: root
    password: Suvam123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true