spring:
  application:
    name: shutterstockApi-prod

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:mysql://localhost:3306/sstk
    username: root
    password: Sstk@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

logging:
  file:
    name: sstk-prod.log