spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/shopnest
    password: Suvam@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
      name: product-module      
    
server:
  port: '8082'

      
# Eureka 
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

okta:
  oauth2:
    issuer: https://dev-52786026.okta.com/oauth2/default
    audience: api://default