spring:
  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-52786026.okta.com/oauth2/default
          audience: api://default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oab12nv73lSfbnwy5d7
            client-secret: U7LT6XEXRXwpJpVhpbdlEnTd5M-4gT6tEjTTDzv6cY1-2tWyAbFAAwqnVf90GFOz
        provider:
          okta:
            issuer-uri: https://dev-52786026.okta.com/oauth2/default

  datasource:
    url: jdbc:mysql://localhost:3306/shopnest
    password: Suvam@123
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

  application:
    name: wishlist-module

server:
  port: '8085'

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

# Okta Configuration
okta:
  oauth2:
    issuer: https://dev-52786026.okta.com/oauth2/default
    audience: api://default
