spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department-service/** 
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee-service/**
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization-service/**
      - id: account-service
        uri: lb://account-service
        predicates:
          - Path=/account-service/**
    
server:
  port: 8899
 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true