# DataSource Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentmodule
    username: root
    password: Root@123

# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
      name: user-module      
  
# Server Configuration
server:
  port: 9090
 
# Eureka 
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      instance:
      preferIpAddress: true

okta:
  oauth2:
    issuer: https://dev-52786026.okta.com/oauth2/default
    audience: api://default
        